"""Add thumbnail column to Item

Revision ID: 7beea8ccc461
Revises: 9516d6feb4bd
Create Date: 2024-07-07 17:56:31.685271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7beea8ccc461'
down_revision = '9516d6feb4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.Text(), nullable=True))
        batch_op.alter_column('article_number',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('size_in_inches',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_constraint('item_article_number_key', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint('item_article_number_key', ['article_number'])
        batch_op.alter_column('weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('size_in_inches',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('article_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
